Update remaining Mac bots to 10.13.6, except iOS builds.
iOS builds still causing an error on installation:
ERROR: Install failed. Got error "APIInternalError".

stephana will help with debugging this when he's back in the office.

Bug: chromium:862292
Change-Id: I8fdff24938f000da550e1c5420c7ac312f09dce7
Reviewed-on: https://skia-review.googlesource.com/144440
Auto-Submit: Ben Wagner <benjaminwagner@google.com>
Commit-Queue: Eric Boren <borenet@google.com>
Reviewed-by: Eric Boren <borenet@google.com>