Fix Fuchsia roll
It is dying with the error:

src/svg/SkSVGDevice.cpp:870:23: error: binding reference member 'fOrigin' to stack allocated parameter 'origin' [-Werror,-Wdangling-field]
            : fOrigin(origin)
                      ^~~~~~
src/svg/SkSVGDevice.cpp:941:21: note: reference member declared here
    const SkPoint&  fOrigin;

and was introduced in:

https://skia-review.googlesource.com/c/skia/+/150542 (Remove drawPosText from svg)

Change-Id: I7a2d1c2992100d0cfd2e50df6dd7195f62d053e6
Reviewed-on: https://skia-review.googlesource.com/150842
Reviewed-by: Mike Klein <mtklein@google.com>
Commit-Queue: Mike Klein <mtklein@google.com>