Revert of nanobench: turn on f16 and sRGB on the bots (patchset #1 id:1 of https://codereview.chromium.org/1769163006/ )
Reason for revert:
Debug bots failing at
   Running writepix_RGBA_UPM	f16

../../../src/core/SkBitmap.cpp:558: fatal error: ""false && \"Can't return addr for config\"""

Original issue's description:
> nanobench: turn on f16 and sRGB on the bots
>
> BUG=skia:
> GOLD_TRYBOT_URL= https://gold.skia.org/search2?unt=true&query=source_type%3Dgm&master=false&issue=1769163006
>
> Committed: https://skia.googlesource.com/skia/+/6b5c5cc7b7bdffb4882706b915b544aba8714961

TBR=reed@google.com,mtklein@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=skia:

Review URL: https://codereview.chromium.org/1780463003