Revert of Enable RAW codec for Windows (patchset #8 id:140001 of https://codereview.chromium.org/1738913002/ )
Reason for revert:
I don't think there's anything wrong with this per-se, but the 32-bit Windows bots are running out of memory while running these tests now.

(You'll see something like c:\0\build\slave\workdir\build\skia\include\core\skbitmap.h:247: fatal error: ""sk_throw"" in the log.)

We run these tests in parallel, and sometimes these 32-bit processes try to use more than the 2-3G RAM they can allocate.  Seems like this is a particularly memory-intense process?

If we reland this, we might want to blacklist these tests on the 32-bit Windows bots.  The 64-bit bots should have access to tons and tons of RAM and let us keep testing for Windows.

Original issue's description:
> Enable RAW codec for Windows
>
> * Fix the exception catching
> * Set preprocessor differently for MSVC
>
> BUG=skia:4889(b/26958348)
> GOLD_TRYBOT_URL= https://gold.skia.org/search2?unt=true&query=source_type%3Dgm&master=false&issue=1738913002
>
> Committed: https://skia.googlesource.com/skia/+/474e4c3dd28b67f590851321f15d9983ef7fd031

TBR=scroggo@google.com,msarett@google.com,yujieqin@google.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=skia:4889(b/26958348)

Review URL: https://codereview.chromium.org/1747443003