Fix pessimizing move in SamplePictFile
../../samplecode/SamplePictFile.cpp:194:20: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
            return std::move(pic);
                               ^

R=reed@google.com,mtklein@google.com
GOLD_TRYBOT_URL= https://gold.skia.org/search2?unt=true&query=source_type%3Dgm&master=false&issue=1809943005

Review URL: https://codereview.chromium.org/1809943005