Revert "Don't execute onFlush op lists until after GPU data is uploaded"
This reverts commit 374a4e49e47a2f1f793a4673f285984953a73308.

Reason for revert: lots of failures across the board.  Here's one:

../../../src/gpu/GrDrawingManager.cpp:203: fatal error: "assert(onFlushOpList->unique())"


Original change's description:
> Don't execute onFlush op lists until after GPU data is uploaded
> 
> Bug: skia:
> Change-Id: I2ea15f67466761ebd24b9d4a8eb51cd2d452be3c
> Reviewed-on: https://skia-review.googlesource.com/54942
> Reviewed-by: Robert Phillips <robertphillips@google.com>
> Commit-Queue: Chris Dalton <csmartdalton@google.com>

TBR=robertphillips@google.com,csmartdalton@google.com

Change-Id: I3f9de3708dd925c93aefc1e6fe8a48833de9171b
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: skia:
Reviewed-on: https://skia-review.googlesource.com/55600
Reviewed-by: Mike Klein <mtklein@google.com>
Commit-Queue: Mike Klein <mtklein@google.com>